import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const ROOT='https://www.40daysofholiness.com/';
const DOMAIN='www.40daysofholiness.com';
const out=resolve('migration');
const decode=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();
const vals=(html,re)=>[...html.matchAll(re)].map(m=>decode(m[1]));
const attr=(tag,name)=>{const m=tag.match(new RegExp(`\\s${name}=["']([^"']*)["']`,'i'));return m?decode(m[1]):''};
const absolute=(v,base=ROOT)=>{try{const u=new URL(v,base);u.hash='';if(u.hostname==='40daysofholiness.com')u.hostname=DOMAIN;if(u.hostname===DOMAIN)u.protocol='https:';return u.href}catch{return v}};
const csv=v=>'"'+String(v??'').replaceAll('"','""')+'"';
const writeCsv=async(name,fields,rows)=>writeFile(resolve(out,name),'\uFEFF'+fields.map(csv).join(',')+'\n'+(rows.length?rows.map(r=>fields.map(f=>csv(r[f])).join(',')).join('\n')+'\n':''));
const get=async url=>{try{const r=await fetch(url,{redirect:'follow',headers:{'user-agent':'40DaysOfHolinessMigrationInventory/1.0 (read-only owner-authorized crawl)'}});return {status:r.status,final:absolute(r.url),type:r.headers.get('content-type')||'',body:await r.text()}}catch(e){return {status:0,final:url,type:'',body:String(e.message)}}};

const sitemapQueue=[ROOT+'sitemap.xml'], sitemapSeen=new Set(), seeds=new Set(); let smIndex=0;
while(sitemapQueue.length){const url=sitemapQueue.shift();if(sitemapSeen.has(url))continue;sitemapSeen.add(url);const r=await get(url);await writeFile(resolve(out,smIndex++?'sitemap-'+String(smIndex-1).padStart(2,'0')+'.xml':'sitemap-source.xml'),r.body);const locs=vals(r.body,/<loc>([\s\S]*?)<\/loc>/gi).map(x=>absolute(x));if(/<sitemapindex/i.test(r.body))sitemapQueue.push(...locs);else locs.forEach(x=>seeds.add(x));}
seeds.add(ROOT);
// Public routes exposed by the Wix router but omitted from XML sitemaps/navigation.
for(const path of ['/home','/search','/fullscreen-page','/congrats'])seeds.add(new URL(path,ROOT).href);
const queue=[...seeds].sort(), seen=new Set(), pages=[], links=[], videos=[], assets=[], seo=[], redirects=[];
const downloadable=/\.(pdf|docx?|xlsx?|pptx?|zip|epub|mp3|mp4|m4a)([?#]|$)/i;
while(queue.length&&seen.size<1000){const url=absolute(queue.shift());if(seen.has(url))continue;seen.add(url);const r=await get(url);console.error(r.status,url);if(r.final!==url)redirects.push({old_url:url,destination_url:r.final,http_status:r.status,source:'PUBLIC_HTTP',external_dependency:'UNKNOWN',url_priority:'NORMAL',proposed_url:'',reason:'',seo_rationale:'',dependencies:'',risk:'',required_direct_301:'YES',owner_decision_status:'PENDING_OWNER_REVIEW',notes:'Observed during crawl; Wix redirect export still required.'});if(!/html/i.test(r.type)&&!/<html/i.test(r.body))continue;const h=r.body;
  const title=decode((h.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]);
  const metas={};for(const m of h.matchAll(/<meta\b[^>]*>/gi)){const t=m[0],k=(attr(t,'name')||attr(t,'property')||attr(t,'http-equiv')).toLowerCase();if(k)metas[k]=attr(t,'content')}
  const canonical=absolute(attr((h.match(/<link\b[^>]*rel=["'][^"']*canonical[^"']*["'][^>]*>/i)||h.match(/<link\b[^>]*href=["'][^"']+["'][^>]*rel=["'][^"']*canonical[^"']*["'][^>]*>/i)||[])[0]||'','href'),r.final);
  const hs=n=>vals(h,new RegExp(`<h${n}\\b[^>]*>([\\s\\S]*?)<\\/h${n}>`,'gi'));
  const internal=[],outbound=[],downloads=[],ctas=[];
  for(const m of h.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const dest=absolute(decode(m[1]),r.final),text=decode(m[2]),host=(()=>{try{return new URL(dest).hostname}catch{return''}})(),kind=host===DOMAIN||host==='40daysofholiness.com'?'internal':'outbound';(kind==='internal'?internal:outbound).push(dest);if(downloadable.test(dest))downloads.push(dest);else if(kind==='internal'&&/^https?:/.test(dest))queue.push(dest);if(text)ctas.push(text);links.push({source_url:url,destination_url:dest,link_type:kind,anchor_text:text,rel:attr(m[0],'rel'),is_download:downloadable.test(dest)?'YES':'NO',qa_status:'NOT_TESTED',notes:''})}
  const imgs=[];for(const m of h.matchAll(/<img\b[^>]*>/gi)){const src=attr(m[0],'src')||attr(m[0],'data-src');if(!src)continue;const item={url:absolute(src,r.final),alt:attr(m[0],'alt')};imgs.push(item);assets.push({page_url:url,asset_type:'IMAGE',source_url:item.url,alt_text:item.alt,local_path:'',http_status:'NOT_CHECKED',migration_stage:'DISCOVERED',qa_status:'NOT_TESTED',owner_decision_status:'PENDING_OWNER_REVIEW',notes:''})}
  const iframeUrls=[...h.matchAll(/<iframe\b[^>]*>/gi)].map(m=>absolute(attr(m[0],'src'),r.final)).filter(Boolean),v=[];for(const candidate of iframeUrls.concat(internal,outbound)){const m=candidate.match(/(?:player\.)?vimeo\.com\/(?:video\/)?(\d+)/i);if(m&&!v.some(x=>x.id===m[1]))v.push({id:m[1],embed:candidate})}for(const x of v)videos.push({page_url:url,provider:'VIMEO',video_id:x.id,embed_url:x.embed,title:'',transcript_status:'NOT_AUTHORIZED',migration_stage:'VIDEO_IDENTIFIED',qa_status:'NOT_TESTED',owner_decision_status:'PENDING_OWNER_REVIEW',notes:'ID discovered from public embed; no Vimeo API call made.'});
  const forms=[...h.matchAll(/<form\b[^>]*>/gi)].map(m=>({action:absolute(attr(m[0],'action')||r.final,r.final),method:(attr(m[0],'method')||'GET').toUpperCase()}));const buttons=vals(h,/<button\b[^>]*>([\s\S]*?)<\/button>/gi);const jsonld=vals(h,/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi);const body=decode((h.match(/<body\b[^>]*>([\s\S]*?)<\/body>/i)||[])[1]).slice(0,1200);const og=JSON.stringify(Object.fromEntries(Object.entries(metas).filter(([k])=>k.startsWith('og:'))));const social=JSON.stringify(Object.fromEntries(Object.entries(metas).filter(([k])=>k.startsWith('twitter:'))));
  const row={existing_url:url,slug:new URL(url).pathname||'/',http_status:r.status,final_url:r.final,title,meta_description:metas.description||'',canonical_url:canonical,h1:hs(1).join(' | '),h2_headings:hs(2).join(' | '),h3_headings:hs(3).join(' | '),body_summary:body,internal_links:[...new Set(internal)].join(' | '),outbound_links:[...new Set(outbound)].join(' | '),images_and_alt_text:JSON.stringify(imgs),video_embeds:v.map(x=>x.embed).join(' | '),forms:JSON.stringify(forms),ctas_and_buttons:[...new Set(buttons.concat(ctas))].join(' | '),downloadable_files:[...new Set(downloads)].join(' | '),open_graph_metadata:og,social_metadata:social,robots_directives:metas.robots||'',structured_data:jsonld.join(' | '),special_functionality:iframeUrls.join(' | '),discovery_sources:seeds.has(url)?'XML_SITEMAP':'INTERNAL_LINK',migration_stage:v.length?'VIDEO_IDENTIFIED':'BASELINE_CAPTURED',qa_status:'NOT_TESTED',owner_decision_status:'PENDING_OWNER_REVIEW',slug_change_proposal:'',notes:'Server-rendered public HTML baseline.'};pages.push(row);seo.push({url,http_status:r.status,title,meta_description:row.meta_description,canonical_url:canonical,h1:row.h1,robots_directives:row.robots_directives,open_graph_metadata:og,social_metadata:social,structured_data:row.structured_data,captured_at_utc:new Date().toISOString(),qa_status:'NOT_TESTED',notes:''});}
const fields=o=>Object.keys(o[0]||{});await writeCsv('pages.csv',fields(pages).length?fields(pages):['existing_url'],pages);await writeCsv('links.csv',['source_url','destination_url','link_type','anchor_text','rel','is_download','qa_status','notes'],links);await writeCsv('videos.csv',['page_url','provider','video_id','embed_url','title','transcript_status','migration_stage','qa_status','owner_decision_status','notes'],videos);await writeCsv('assets.csv',['page_url','asset_type','source_url','alt_text','local_path','http_status','migration_stage','qa_status','owner_decision_status','notes'],assets);await writeCsv('seo-baseline.csv',fields(seo).length?fields(seo):['url'],seo);await writeCsv('redirects.csv',['old_url','destination_url','http_status','source','external_dependency','url_priority','proposed_url','reason','seo_rationale','dependencies','risk','required_direct_301','owner_decision_status','notes'],redirects);
await writeFile(resolve(out,'crawl-summary.json'),JSON.stringify({root:ROOT,pages:pages.length,links:links.length,videos:videos.length,unique_video_ids:new Set(videos.map(v=>v.video_id)).size,assets:assets.length,redirects_observed:redirects.length,sitemaps:[...sitemapSeen],limitations:['Public crawl cannot discover unlinked Wix redirects.','Owner URL lists, Wix redirect export, Search Console, analytics, backlinks, books, workbooks, QR codes, emails, and ads remain external inputs.','Rendered client-only interactions require later visual/browser QA.']},null,2));
